// Run against a demo server: RUNNER_ROOM_TEST_URL=http://127.0.0.1:8080 node tests/dashboard.cjs
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
require('node:fs').mkdirSync('artifacts', {recursive:true});
(async () => {
  const browser = await chromium.launch({channel:'chrome', headless:true});
  try {
    const context = await browser.newContext({viewport:{width:1440,height:1000}});
    const page = await context.newPage(), errors = [];
    page.on('pageerror', e => errors.push(e.message));
    const base = process.env.RUNNER_ROOM_TEST_URL || 'http://127.0.0.1:8080';
    await page.goto(base); await page.locator('.runner-row').first().waitFor();
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'dark');
    assert.equal(await page.locator('.widget-frame').count(), 7);
    await page.locator('#preferences-open').click();
    await page.locator('#pref-theme').selectOption('night'); await page.locator('#pref-clock').selectOption('12');
    await page.locator('#pref-language').selectOption('pt-PT');
    await page.waitForFunction(() => document.documentElement.lang === 'pt-PT');
    assert.equal(await page.locator('#preferences-title').textContent(),'Preferências');
    await page.locator('#pref-language').selectOption('en');
    await page.locator('#edit-layout').click();
    const server = page.locator('[data-widget="server"]');
    await server.locator('[data-action="pin"]').click();
    assert.equal(await page.locator('.widget-frame').first().getAttribute('data-widget'), 'server');
    await server.locator('[data-action="collapse"]').click();
    assert.equal(await server.locator('.widget-body').isVisible(), false);
    await page.locator('[data-widget="activity"] [data-action="hide"]').click();
    await page.reload(); await page.locator('.runner-row').first().waitFor();
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'night');
    assert.equal(await server.locator('.widget-body').isVisible(), false);
    assert.equal(await page.locator('[data-widget="activity"]').isVisible(), false);
    await page.locator('#search').fill('api'); await page.reload(); await page.locator('.runner-row').first().waitFor();
    assert.equal(await page.locator('#search').inputValue(), 'api'); await page.locator('#search').fill('');
    await page.locator('.runner-toggle').first().click(); await page.getByRole('link', {name:'Open runner page',exact:true}).first().click();
    await page.waitForFunction(() => !document.querySelector('#workspace-detail').hidden && document.querySelector('#detail-message').textContent === '');
    assert.match(page.url(), /#\/runner\//); await page.reload();
    await page.locator('#detail-content .runner-details').waitFor();
    await page.goto(base + '/#/server'); await page.locator('#detail-content .monitor-table').waitFor();
    assert.match(await page.locator('#detail-content').textContent(), /GiB/);
    await page.goto(base + '/#history'); await page.locator('#history-jobs a').first().waitFor();
    await page.locator('#history-jobs a').first().click(); await page.waitForFunction(() => document.querySelector('#detail-message').textContent === '');
    assert.match(await page.locator('#detail-content').textContent(), /Outcome/);
    await page.goto(base + '/#overview'); await page.locator('.target-column a').first().waitFor();
    await page.locator('.target-column a').first().click(); await page.locator('#detail-content table').waitFor();
    await page.goto(base + '/#overview'); await page.locator('#preferences-open').click();
    await page.locator('#pref-theme').selectOption('system'); await page.emulateMedia({colorScheme:'light'});
    assert.equal(await page.locator('html').getAttribute('data-theme'), 'light');
    await page.locator('#pref-display').selectOption('tv'); await page.locator('#preferences-close').click();
    await page.locator('#exit-tv').click(); assert.equal(await page.locator('html').getAttribute('data-display'), 'normal');
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.locator('#preferences-open').click(); await page.locator('#pref-display').selectOption('compact');
    await page.locator('#preferences-close').click();
    await page.screenshot({path:'artifacts/interfaces-mobile.png', fullPage:true});
    await page.setViewportSize({width:1440,height:1000}); await page.screenshot({path:'artifacts/interfaces-desktop.png', fullPage:true});
    const manifest = await (await context.request.get(base + '/manifest.webmanifest')).json(); assert.equal(manifest.display, 'standalone');
    await page.evaluate(() => navigator.serviceWorker.ready);
    const cached = await page.evaluate(async () => (await Promise.all((await caches.keys()).map(async k => (await (await caches.open(k)).keys()).map(r => new URL(r.url).pathname)))).flat());
    assert.ok(cached.includes('/offline.html')); assert.ok(!cached.some(p => p.startsWith('/api/') || p === '/' || p === '/index.html'));
    await context.setOffline(true); await page.goto(base); await page.getByText('Server unreachable', {exact:true}).waitFor();
    await context.setOffline(false); await page.getByRole('link', {name:'Reconnect'}).click(); await page.locator('.runner-row').first().waitFor();
    // A larger fleet verifies page bounds, saved page, and filtering resets.
    const response = await context.request.get(base + '/api/runners'); const fleet = await response.json();
    fleet.runners = Array.from({length:23}, (_, i) => ({...fleet.runners[0], id:String(i).padStart(64,'0'), path:'/sample/'+i, displayName:'Runner '+String(i).padStart(2,'0'), repository:'sample/project', currentJob:null}));
    await page.route('**/api/runners', r => r.fulfill({json:fleet}));
    await page.goto(base + '/#overview'); await page.waitForFunction(() => document.querySelector('#count').textContent === '23');
    assert.equal(await page.locator('.runner-row').count(),10); await page.locator('#runner-next').click();
    assert.match(await page.locator('.runner-row').first().textContent(), /Runner 10/);
    await page.reload(); await page.waitForFunction(() => document.querySelector('#runner-page').textContent === '2 / 3');
    await page.locator('#runner-next').click(); assert.equal(await page.locator('.runner-row').count(),3);
    await page.locator('#search').fill('Runner 00'); assert.equal(await page.locator('.runner-row').count(),1);
    assert.equal(await page.locator('#runner-page').textContent(),'1 / 1');
    await page.goto(base + '/#/job/not-a-real-job'); await page.getByText('Details unavailable',{exact:true}).waitFor();
    assert.deepEqual(errors, []); console.log('PASS: details, layout/prefs persistence, translation, themes, compact/TV, mobile, PWA and safe offline behavior.');
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exit(1); });
